/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderProviderSetupRouteImport } from './routes/provider/provider-setup'
import { Route as ProviderLayoutRouteImport } from './routes/provider/_layout'
import { Route as OwnerSettingsRouteImport } from './routes/owner/settings'
import { Route as OwnerOwnerSetupRouteImport } from './routes/owner/owner-setup'
import { Route as OwnerLayoutRouteImport } from './routes/owner/_layout'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as ProviderLayoutDashboardRouteImport } from './routes/provider/_layout/dashboard'
import { Route as OwnerLayoutNotificationsRouteImport } from './routes/owner/_layout/notifications'
import { Route as OwnerLayoutDashboardRouteImport } from './routes/owner/_layout/dashboard'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin/_layout/dashboard'
import { Route as ProviderLayoutJobsIndexRouteImport } from './routes/provider/_layout/jobs/index'
import { Route as OwnerLayoutVehiclesIndexRouteImport } from './routes/owner/_layout/vehicles/index'
import { Route as OwnerLayoutRequestsIndexRouteImport } from './routes/owner/_layout/requests/index'
import { Route as OwnerLayoutProvidersIndexRouteImport } from './routes/owner/_layout/providers/index'
import { Route as OwnerLayoutJobsIndexRouteImport } from './routes/owner/_layout/jobs/index'
import { Route as ProviderLayoutRequestsRequestIdRouteImport } from './routes/provider/_layout/requests/$requestId'
import { Route as ProviderLayoutJobsJobIdRouteImport } from './routes/provider/_layout/jobs/$jobId'
import { Route as OwnerLayoutVehiclesNewRouteImport } from './routes/owner/_layout/vehicles/new'
import { Route as OwnerLayoutVehiclesVehicleIdRouteImport } from './routes/owner/_layout/vehicles/$vehicleId'
import { Route as OwnerLayoutRequestsNewRouteImport } from './routes/owner/_layout/requests/new'
import { Route as OwnerLayoutRequestsRequestIdRouteImport } from './routes/owner/_layout/requests/$requestId'
import { Route as OwnerLayoutProvidersProviderIdRouteImport } from './routes/owner/_layout/providers/$providerId'
import { Route as OwnerLayoutJobsJobIdRouteImport } from './routes/owner/_layout/jobs/$jobId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderProviderSetupRoute = ProviderProviderSetupRouteImport.update({
  id: '/provider/provider-setup',
  path: '/provider/provider-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderLayoutRoute = ProviderLayoutRouteImport.update({
  id: '/provider/_layout',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOwnerSetupRoute = OwnerOwnerSetupRouteImport.update({
  id: '/owner/owner-setup',
  path: '/owner/owner-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLayoutRoute = OwnerLayoutRouteImport.update({
  id: '/owner/_layout',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderLayoutDashboardRoute = ProviderLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProviderLayoutRoute,
} as any)
const OwnerLayoutNotificationsRoute =
  OwnerLayoutNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => OwnerLayoutRoute,
  } as any)
const OwnerLayoutDashboardRoute = OwnerLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OwnerLayoutRoute,
} as any)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const ProviderLayoutJobsIndexRoute = ProviderLayoutJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => ProviderLayoutRoute,
} as any)
const OwnerLayoutVehiclesIndexRoute =
  OwnerLayoutVehiclesIndexRouteImport.update({
    id: '/vehicles/',
    path: '/vehicles/',
    getParentRoute: () => OwnerLayoutRoute,
  } as any)
const OwnerLayoutRequestsIndexRoute =
  OwnerLayoutRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => OwnerLayoutRoute,
  } as any)
const OwnerLayoutProvidersIndexRoute =
  OwnerLayoutProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => OwnerLayoutRoute,
  } as any)
const OwnerLayoutJobsIndexRoute = OwnerLayoutJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => OwnerLayoutRoute,
} as any)
const ProviderLayoutRequestsRequestIdRoute =
  ProviderLayoutRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => ProviderLayoutRoute,
  } as any)
const ProviderLayoutJobsJobIdRoute = ProviderLayoutJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => ProviderLayoutRoute,
} as any)
const OwnerLayoutVehiclesNewRoute = OwnerLayoutVehiclesNewRouteImport.update({
  id: '/vehicles/new',
  path: '/vehicles/new',
  getParentRoute: () => OwnerLayoutRoute,
} as any)
const OwnerLayoutVehiclesVehicleIdRoute =
  OwnerLayoutVehiclesVehicleIdRouteImport.update({
    id: '/vehicles/$vehicleId',
    path: '/vehicles/$vehicleId',
    getParentRoute: () => OwnerLayoutRoute,
  } as any)
const OwnerLayoutRequestsNewRoute = OwnerLayoutRequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => OwnerLayoutRoute,
} as any)
const OwnerLayoutRequestsRequestIdRoute =
  OwnerLayoutRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => OwnerLayoutRoute,
  } as any)
const OwnerLayoutProvidersProviderIdRoute =
  OwnerLayoutProvidersProviderIdRouteImport.update({
    id: '/providers/$providerId',
    path: '/providers/$providerId',
    getParentRoute: () => OwnerLayoutRoute,
  } as any)
const OwnerLayoutJobsJobIdRoute = OwnerLayoutJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => OwnerLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/owner': typeof OwnerLayoutRouteWithChildren
  '/owner/owner-setup': typeof OwnerOwnerSetupRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/provider': typeof ProviderLayoutRouteWithChildren
  '/provider/provider-setup': typeof ProviderProviderSetupRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/owner/dashboard': typeof OwnerLayoutDashboardRoute
  '/owner/notifications': typeof OwnerLayoutNotificationsRoute
  '/provider/dashboard': typeof ProviderLayoutDashboardRoute
  '/owner/jobs/$jobId': typeof OwnerLayoutJobsJobIdRoute
  '/owner/providers/$providerId': typeof OwnerLayoutProvidersProviderIdRoute
  '/owner/requests/$requestId': typeof OwnerLayoutRequestsRequestIdRoute
  '/owner/requests/new': typeof OwnerLayoutRequestsNewRoute
  '/owner/vehicles/$vehicleId': typeof OwnerLayoutVehiclesVehicleIdRoute
  '/owner/vehicles/new': typeof OwnerLayoutVehiclesNewRoute
  '/provider/jobs/$jobId': typeof ProviderLayoutJobsJobIdRoute
  '/provider/requests/$requestId': typeof ProviderLayoutRequestsRequestIdRoute
  '/owner/jobs': typeof OwnerLayoutJobsIndexRoute
  '/owner/providers': typeof OwnerLayoutProvidersIndexRoute
  '/owner/requests': typeof OwnerLayoutRequestsIndexRoute
  '/owner/vehicles': typeof OwnerLayoutVehiclesIndexRoute
  '/provider/jobs': typeof ProviderLayoutJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/owner': typeof OwnerLayoutRouteWithChildren
  '/owner/owner-setup': typeof OwnerOwnerSetupRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/provider': typeof ProviderLayoutRouteWithChildren
  '/provider/provider-setup': typeof ProviderProviderSetupRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/owner/dashboard': typeof OwnerLayoutDashboardRoute
  '/owner/notifications': typeof OwnerLayoutNotificationsRoute
  '/provider/dashboard': typeof ProviderLayoutDashboardRoute
  '/owner/jobs/$jobId': typeof OwnerLayoutJobsJobIdRoute
  '/owner/providers/$providerId': typeof OwnerLayoutProvidersProviderIdRoute
  '/owner/requests/$requestId': typeof OwnerLayoutRequestsRequestIdRoute
  '/owner/requests/new': typeof OwnerLayoutRequestsNewRoute
  '/owner/vehicles/$vehicleId': typeof OwnerLayoutVehiclesVehicleIdRoute
  '/owner/vehicles/new': typeof OwnerLayoutVehiclesNewRoute
  '/provider/jobs/$jobId': typeof ProviderLayoutJobsJobIdRoute
  '/provider/requests/$requestId': typeof ProviderLayoutRequestsRequestIdRoute
  '/owner/jobs': typeof OwnerLayoutJobsIndexRoute
  '/owner/providers': typeof OwnerLayoutProvidersIndexRoute
  '/owner/requests': typeof OwnerLayoutRequestsIndexRoute
  '/owner/vehicles': typeof OwnerLayoutVehiclesIndexRoute
  '/provider/jobs': typeof ProviderLayoutJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/owner/_layout': typeof OwnerLayoutRouteWithChildren
  '/owner/owner-setup': typeof OwnerOwnerSetupRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/provider/_layout': typeof ProviderLayoutRouteWithChildren
  '/provider/provider-setup': typeof ProviderProviderSetupRoute
  '/admin/_layout/dashboard': typeof AdminLayoutDashboardRoute
  '/owner/_layout/dashboard': typeof OwnerLayoutDashboardRoute
  '/owner/_layout/notifications': typeof OwnerLayoutNotificationsRoute
  '/provider/_layout/dashboard': typeof ProviderLayoutDashboardRoute
  '/owner/_layout/jobs/$jobId': typeof OwnerLayoutJobsJobIdRoute
  '/owner/_layout/providers/$providerId': typeof OwnerLayoutProvidersProviderIdRoute
  '/owner/_layout/requests/$requestId': typeof OwnerLayoutRequestsRequestIdRoute
  '/owner/_layout/requests/new': typeof OwnerLayoutRequestsNewRoute
  '/owner/_layout/vehicles/$vehicleId': typeof OwnerLayoutVehiclesVehicleIdRoute
  '/owner/_layout/vehicles/new': typeof OwnerLayoutVehiclesNewRoute
  '/provider/_layout/jobs/$jobId': typeof ProviderLayoutJobsJobIdRoute
  '/provider/_layout/requests/$requestId': typeof ProviderLayoutRequestsRequestIdRoute
  '/owner/_layout/jobs/': typeof OwnerLayoutJobsIndexRoute
  '/owner/_layout/providers/': typeof OwnerLayoutProvidersIndexRoute
  '/owner/_layout/requests/': typeof OwnerLayoutRequestsIndexRoute
  '/owner/_layout/vehicles/': typeof OwnerLayoutVehiclesIndexRoute
  '/provider/_layout/jobs/': typeof ProviderLayoutJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/owner'
    | '/owner/owner-setup'
    | '/owner/settings'
    | '/provider'
    | '/provider/provider-setup'
    | '/admin/dashboard'
    | '/owner/dashboard'
    | '/owner/notifications'
    | '/provider/dashboard'
    | '/owner/jobs/$jobId'
    | '/owner/providers/$providerId'
    | '/owner/requests/$requestId'
    | '/owner/requests/new'
    | '/owner/vehicles/$vehicleId'
    | '/owner/vehicles/new'
    | '/provider/jobs/$jobId'
    | '/provider/requests/$requestId'
    | '/owner/jobs'
    | '/owner/providers'
    | '/owner/requests'
    | '/owner/vehicles'
    | '/provider/jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/owner'
    | '/owner/owner-setup'
    | '/owner/settings'
    | '/provider'
    | '/provider/provider-setup'
    | '/admin/dashboard'
    | '/owner/dashboard'
    | '/owner/notifications'
    | '/provider/dashboard'
    | '/owner/jobs/$jobId'
    | '/owner/providers/$providerId'
    | '/owner/requests/$requestId'
    | '/owner/requests/new'
    | '/owner/vehicles/$vehicleId'
    | '/owner/vehicles/new'
    | '/provider/jobs/$jobId'
    | '/provider/requests/$requestId'
    | '/owner/jobs'
    | '/owner/providers'
    | '/owner/requests'
    | '/owner/vehicles'
    | '/provider/jobs'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/admin/_layout'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/owner/_layout'
    | '/owner/owner-setup'
    | '/owner/settings'
    | '/provider/_layout'
    | '/provider/provider-setup'
    | '/admin/_layout/dashboard'
    | '/owner/_layout/dashboard'
    | '/owner/_layout/notifications'
    | '/provider/_layout/dashboard'
    | '/owner/_layout/jobs/$jobId'
    | '/owner/_layout/providers/$providerId'
    | '/owner/_layout/requests/$requestId'
    | '/owner/_layout/requests/new'
    | '/owner/_layout/vehicles/$vehicleId'
    | '/owner/_layout/vehicles/new'
    | '/provider/_layout/jobs/$jobId'
    | '/provider/_layout/requests/$requestId'
    | '/owner/_layout/jobs/'
    | '/owner/_layout/providers/'
    | '/owner/_layout/requests/'
    | '/owner/_layout/vehicles/'
    | '/provider/_layout/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  OwnerLayoutRoute: typeof OwnerLayoutRouteWithChildren
  OwnerOwnerSetupRoute: typeof OwnerOwnerSetupRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  ProviderLayoutRoute: typeof ProviderLayoutRouteWithChildren
  ProviderProviderSetupRoute: typeof ProviderProviderSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/provider-setup': {
      id: '/provider/provider-setup'
      path: '/provider/provider-setup'
      fullPath: '/provider/provider-setup'
      preLoaderRoute: typeof ProviderProviderSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/_layout': {
      id: '/provider/_layout'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/owner-setup': {
      id: '/owner/owner-setup'
      path: '/owner/owner-setup'
      fullPath: '/owner/owner-setup'
      preLoaderRoute: typeof OwnerOwnerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/_layout': {
      id: '/owner/_layout'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/_layout/dashboard': {
      id: '/provider/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/provider/dashboard'
      preLoaderRoute: typeof ProviderLayoutDashboardRouteImport
      parentRoute: typeof ProviderLayoutRoute
    }
    '/owner/_layout/notifications': {
      id: '/owner/_layout/notifications'
      path: '/notifications'
      fullPath: '/owner/notifications'
      preLoaderRoute: typeof OwnerLayoutNotificationsRouteImport
      parentRoute: typeof OwnerLayoutRoute
    }
    '/owner/_layout/dashboard': {
      id: '/owner/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerLayoutDashboardRouteImport
      parentRoute: typeof OwnerLayoutRoute
    }
    '/admin/_layout/dashboard': {
      id: '/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/provider/_layout/jobs/': {
      id: '/provider/_layout/jobs/'
      path: '/jobs'
      fullPath: '/provider/jobs'
      preLoaderRoute: typeof ProviderLayoutJobsIndexRouteImport
      parentRoute: typeof ProviderLayoutRoute
    }
    '/owner/_layout/vehicles/': {
      id: '/owner/_layout/vehicles/'
      path: '/vehicles'
      fullPath: '/owner/vehicles'
      preLoaderRoute: typeof OwnerLayoutVehiclesIndexRouteImport
      parentRoute: typeof OwnerLayoutRoute
    }
    '/owner/_layout/requests/': {
      id: '/owner/_layout/requests/'
      path: '/requests'
      fullPath: '/owner/requests'
      preLoaderRoute: typeof OwnerLayoutRequestsIndexRouteImport
      parentRoute: typeof OwnerLayoutRoute
    }
    '/owner/_layout/providers/': {
      id: '/owner/_layout/providers/'
      path: '/providers'
      fullPath: '/owner/providers'
      preLoaderRoute: typeof OwnerLayoutProvidersIndexRouteImport
      parentRoute: typeof OwnerLayoutRoute
    }
    '/owner/_layout/jobs/': {
      id: '/owner/_layout/jobs/'
      path: '/jobs'
      fullPath: '/owner/jobs'
      preLoaderRoute: typeof OwnerLayoutJobsIndexRouteImport
      parentRoute: typeof OwnerLayoutRoute
    }
    '/provider/_layout/requests/$requestId': {
      id: '/provider/_layout/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/provider/requests/$requestId'
      preLoaderRoute: typeof ProviderLayoutRequestsRequestIdRouteImport
      parentRoute: typeof ProviderLayoutRoute
    }
    '/provider/_layout/jobs/$jobId': {
      id: '/provider/_layout/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/provider/jobs/$jobId'
      preLoaderRoute: typeof ProviderLayoutJobsJobIdRouteImport
      parentRoute: typeof ProviderLayoutRoute
    }
    '/owner/_layout/vehicles/new': {
      id: '/owner/_layout/vehicles/new'
      path: '/vehicles/new'
      fullPath: '/owner/vehicles/new'
      preLoaderRoute: typeof OwnerLayoutVehiclesNewRouteImport
      parentRoute: typeof OwnerLayoutRoute
    }
    '/owner/_layout/vehicles/$vehicleId': {
      id: '/owner/_layout/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/owner/vehicles/$vehicleId'
      preLoaderRoute: typeof OwnerLayoutVehiclesVehicleIdRouteImport
      parentRoute: typeof OwnerLayoutRoute
    }
    '/owner/_layout/requests/new': {
      id: '/owner/_layout/requests/new'
      path: '/requests/new'
      fullPath: '/owner/requests/new'
      preLoaderRoute: typeof OwnerLayoutRequestsNewRouteImport
      parentRoute: typeof OwnerLayoutRoute
    }
    '/owner/_layout/requests/$requestId': {
      id: '/owner/_layout/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/owner/requests/$requestId'
      preLoaderRoute: typeof OwnerLayoutRequestsRequestIdRouteImport
      parentRoute: typeof OwnerLayoutRoute
    }
    '/owner/_layout/providers/$providerId': {
      id: '/owner/_layout/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/owner/providers/$providerId'
      preLoaderRoute: typeof OwnerLayoutProvidersProviderIdRouteImport
      parentRoute: typeof OwnerLayoutRoute
    }
    '/owner/_layout/jobs/$jobId': {
      id: '/owner/_layout/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/owner/jobs/$jobId'
      preLoaderRoute: typeof OwnerLayoutJobsJobIdRouteImport
      parentRoute: typeof OwnerLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutDashboardRoute: typeof AdminLayoutDashboardRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutDashboardRoute: AdminLayoutDashboardRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface OwnerLayoutRouteChildren {
  OwnerLayoutDashboardRoute: typeof OwnerLayoutDashboardRoute
  OwnerLayoutNotificationsRoute: typeof OwnerLayoutNotificationsRoute
  OwnerLayoutJobsJobIdRoute: typeof OwnerLayoutJobsJobIdRoute
  OwnerLayoutProvidersProviderIdRoute: typeof OwnerLayoutProvidersProviderIdRoute
  OwnerLayoutRequestsRequestIdRoute: typeof OwnerLayoutRequestsRequestIdRoute
  OwnerLayoutRequestsNewRoute: typeof OwnerLayoutRequestsNewRoute
  OwnerLayoutVehiclesVehicleIdRoute: typeof OwnerLayoutVehiclesVehicleIdRoute
  OwnerLayoutVehiclesNewRoute: typeof OwnerLayoutVehiclesNewRoute
  OwnerLayoutJobsIndexRoute: typeof OwnerLayoutJobsIndexRoute
  OwnerLayoutProvidersIndexRoute: typeof OwnerLayoutProvidersIndexRoute
  OwnerLayoutRequestsIndexRoute: typeof OwnerLayoutRequestsIndexRoute
  OwnerLayoutVehiclesIndexRoute: typeof OwnerLayoutVehiclesIndexRoute
}

const OwnerLayoutRouteChildren: OwnerLayoutRouteChildren = {
  OwnerLayoutDashboardRoute: OwnerLayoutDashboardRoute,
  OwnerLayoutNotificationsRoute: OwnerLayoutNotificationsRoute,
  OwnerLayoutJobsJobIdRoute: OwnerLayoutJobsJobIdRoute,
  OwnerLayoutProvidersProviderIdRoute: OwnerLayoutProvidersProviderIdRoute,
  OwnerLayoutRequestsRequestIdRoute: OwnerLayoutRequestsRequestIdRoute,
  OwnerLayoutRequestsNewRoute: OwnerLayoutRequestsNewRoute,
  OwnerLayoutVehiclesVehicleIdRoute: OwnerLayoutVehiclesVehicleIdRoute,
  OwnerLayoutVehiclesNewRoute: OwnerLayoutVehiclesNewRoute,
  OwnerLayoutJobsIndexRoute: OwnerLayoutJobsIndexRoute,
  OwnerLayoutProvidersIndexRoute: OwnerLayoutProvidersIndexRoute,
  OwnerLayoutRequestsIndexRoute: OwnerLayoutRequestsIndexRoute,
  OwnerLayoutVehiclesIndexRoute: OwnerLayoutVehiclesIndexRoute,
}

const OwnerLayoutRouteWithChildren = OwnerLayoutRoute._addFileChildren(
  OwnerLayoutRouteChildren,
)

interface ProviderLayoutRouteChildren {
  ProviderLayoutDashboardRoute: typeof ProviderLayoutDashboardRoute
  ProviderLayoutJobsJobIdRoute: typeof ProviderLayoutJobsJobIdRoute
  ProviderLayoutRequestsRequestIdRoute: typeof ProviderLayoutRequestsRequestIdRoute
  ProviderLayoutJobsIndexRoute: typeof ProviderLayoutJobsIndexRoute
}

const ProviderLayoutRouteChildren: ProviderLayoutRouteChildren = {
  ProviderLayoutDashboardRoute: ProviderLayoutDashboardRoute,
  ProviderLayoutJobsJobIdRoute: ProviderLayoutJobsJobIdRoute,
  ProviderLayoutRequestsRequestIdRoute: ProviderLayoutRequestsRequestIdRoute,
  ProviderLayoutJobsIndexRoute: ProviderLayoutJobsIndexRoute,
}

const ProviderLayoutRouteWithChildren = ProviderLayoutRoute._addFileChildren(
  ProviderLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  OwnerLayoutRoute: OwnerLayoutRouteWithChildren,
  OwnerOwnerSetupRoute: OwnerOwnerSetupRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  ProviderLayoutRoute: ProviderLayoutRouteWithChildren,
  ProviderProviderSetupRoute: ProviderProviderSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
